name: process-prices

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout repo content
        uses: actions/checkout@v2 #

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.1'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: produce output files
        run: |
          python3 process.py
          mkdir -p output
          cp *.csv data/*.csv output/

      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
